require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - .git/**/*
    - bin/*

Layout/ArgumentAlignment:
  Enabled: false

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/ClassStructure:
  Enabled: true
  ExpectedOrder:
    - module_inclusion
    - constants
    - association
    - public_attribute_macros
    - public_delegate
    - macros
    - public_class_methods
    - initializer
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods
  Categories:
    association:
      - has_many
      - has_one
      - belongs_to
    attribute_macros:
      - attr_accessor
      - attr_reader
      - attr_writer
    macros:
      - validates
      - validate
    module_inclusion:
      - include
      - prepend
      - extend

Layout/ClosingParenthesisIndentation:
  Exclude:
    - spec/**/*.rb

Layout/EmptyLineAfterGuardClause:
  Exclude:
    - lib/active_ad/base.rb

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  AllowMultipleStyles: true
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Layout/LineLength:
  Max: 160
  AllowedPatterns:
    - !ruby/regexp /\A +(it|describe|context|shared_examples|include_examples|it_behaves_like) ["']/
  Exclude:
    - '**/*.gemspec'

Layout/MultilineMethodCallBraceLayout:
  Exclude:
    - spec/**/*.rb

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceBeforeBlockBraces:
  Exclude:
    - spec/**/*.rb

# Trailing white space is meaningful in code examples.
Layout/TrailingWhitespace:
  AllowInHeredoc: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*.rb

Lint/BooleanSymbol:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - spec/**/*.rb

Lint/InterpolationCheck:
  Exclude:
    - spec/**/*.rb

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - def_matcher
    - def_node_matcher

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - '**/*.rake'
    - spec/**/*.rb
    - '**/*.gemspec'

Metrics/ClassLength:
  Max: 250
  Exclude:
    - lib/active_ad/base.rb

Metrics/CyclomaticComplexity:
  Max: 8
  IgnoredMethods:
    - save

Metrics/MethodLength:
  Max: 50

Metrics/ModuleLength:
  Max: 250
  Exclude:
    - spec/**/*.rb

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Exclude:
    - lib/active_ad/base.rb
  IgnoredMethods:
    - each

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/PredicateName:
  # Method define macros for dynamically generated method.
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search
  AllowedMethods:
    - has_many

Naming/VariableNumber:
  EnforcedStyle: snake_case
  AllowedIdentifiers:
    - business_street2

Performance/RedundantMerge:
  MaxKeyValuePairs: 1

RSpec/AnyInstance:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Max: 30

RSpec/FilePath:
  SpecSuffixOnly: true

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 30

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 7

RSpec/RepeatedDescription:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/BlockDelimiters:
  IgnoredMethods:
    - let_it_be
    - let
    - expect
  Exclude:
    - spec/factories/**/*.rb

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - spec/rails_helper.rb

Style/FormatStringToken:
  Exclude:
    - lib/active_ad/concerns/validationable.rb

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/PreferredHashMethods:
  Enabled: false

Style/RaiseArgs:
  AllowedCompactTypes:
    - ActiveAd::RecordInvalid

Style/RedundantBegin:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_english_names

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/WordArray:
  EnforcedStyle: percent
  Exclude:
    - spec/**/*.rb
